### PR TITLE
Applied patches for embedded PDF viewer

### PR DESCRIPTION
**Pull request by tmcdos**
I have created a new folder PATCHES for the individual patches and then I applied them onto the actual source code. You also have to keep the "viewer.html" in **pdf.js-viewer** synchronized with the same file in **pdf.js/web** source tree. I fixed PRINT and LOAD buttons and checked that viewer works in Chrome, IE and FF (see the screenshots).
chrome
chrome_ver
firefox
ie

### CODE REVIEW

**Comment by moesjarraf** [comment]
@tmcdos It looks good, but why have you added all these new files? Such as `examples/acroforms/forms.js`. These files are not in the upstream. It would be best to keep the amount of changes to a minimum. Are they necessary? I expected only modifications to existing files, but if they are necessary let me know.

**Comment by tmcdos** [comment]
@moesjarraf Please forgive me - when I tried to commit my changes, these files were shown as non-versioned, so I just answered YES to the question should they be included in the version control. I can easily remove them and submit another PR, if you like.

**Comment by moesjarraf** [comment]
@tmcdos Its ok. Also, you don't have to create a new PR, just remove the files and create a new commit on the branch that you used for the PR.

**Comment by tmcdos** [comment]
@moesjarraf Done - the PR now contains only the patches and the relevant modified parts of the source code.

**Comment by moesjarraf** [comment]
@tmcdos Thanks, I will merge it, but could you first remove the `/patches` folder from the PR, because we no longer need it since we work on a fork based on the original source and can resolve diff conflicts easier now.

**Comment by tmcdos** [comment]
@moesjarraf I removed the /patches folder.

**Pull request merged**
